# Base change example

In [5]:
import numpy as np

A = np.array(
    [
        [66, 215],
        [95,38]
    ]
)

spiderman = np.array(
    [160,70]
)

coeffs = np.linalg.solve(A, spiderman)

# Print the result
print("Spider-Man in archetype basis:")
print(f"Doctor Strange component: {coeffs[0]:.3f}")
print(f"Hulk component: {coeffs[1]:.3f}")

# Optional: verify by reconstructing the original vector
reconstructed = A @ coeffs
print("\nReconstructed Spider-Man stats:", reconstructed)



Spider-Man in archetype basis:
Doctor Strange component: 0.501
Hulk component: 0.591

Reconstructed Spider-Man stats: [160.  70.]


In [ ]:
CapAm = np.array([50,40,20,30,10,40,10])
SMan = np.array([30,50,40,40,20,10,40])
Hulk = np.array([30,10,100,75,2,6,30])
Ultron = np.array([20,30,50,100,40,10,4])
MrFant = np.array([10,6,6,20,50,20,30])
Wolverine = np.array([40,30,10,30,6,75,40])
ProfX = np.array([4,10,6,30,40,50,75])

archList = np.array([CapAm, SMan, Hulk, Ultron, MrFant, Wolverine, ProfX])
archBase = archList.T
print(archBase)

# Daredevil
#Dare = np.array([40,40,10,20,6,75,10])

#Thor
#Dare = np.array([100,20,100,100,6,20,50])

#Silversurfer
#Dare = np.array([50,75,100,100,20,75,40])

#Spider Man
Dare = np.array([30,50,40,40,20,10,40])

DDCoef = np.linalg.solve(archBase, Dare)

# Print the result
print("Daredevil in archetype basis:")
print(f"Cap Am component: {DDCoef[0]:.3f}")
print(f"SMan component: {DDCoef[1]:.3f}")
print(f"Hulk component: {DDCoef[2]:.3f}")
print(f"Ultron component: {DDCoef[3]:.3f}")
print(f"MrFant component: {DDCoef[4]:.3f}")
print(f"Wolv component: {DDCoef[5]:.3f}")
print(f"ProfX component: {DDCoef[6]:.3f}")






[[ 50  30  30  20  10  40   4]
 [ 40  50  10  30   6  30  10]
 [ 20  40 100  50   6  10   6]
 [ 30  40  75 100  20  30  30]
 [ 10  20   2  40  50   6  40]
 [ 40  10   6  10  20  75  50]
 [ 10  40  30   4  30  40  75]]
Daredevil in archetype basis:
Cap Am component: -9.052
SMan component: 4.056
Hulk component: 0.208
Ultron component: 0.508
MrFant component: 4.771
Wolv component: 8.625
ProfX component: -7.041
